version: '3.9'

services:

  database:
    image: mariadb:10.1.48
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./data/mariadb/var/lib/mysql:/var/lib/mysql
      - ./data/mariadb/etc/mysql:/etc/mysql

  wordpress:
    depends_on:
      - database
    links:
      - database
    image: wordpress:5.7-php7.4-apache
    ports:
      - "8080:80"
      - "8443:443"
    restart: always
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./data/wordpress/var/www/html:/var/www/html

volumes:
  wordpress:
  database:
